openapi: 3.0.3
info:
  title: Email Validation API
  version: 1.0.0
  description: API for validating single and bulk emails with optional SMTP probe
  contact:
    email: contact.emailapi@gmail.com
servers:
  - url: https://e-mailvalidator-production.up.railway.app/
components:
  securitySchemes:
    RapidAPIKey:
      type: apiKey
      in: header
      name: x-rapidapi-key
  schemas:
    EmailCheckResult:
      type: object
      properties:
        syntaxValid:
          type: boolean
          example: true
        mx:
          type: object
          properties:
            ok:
              type: boolean
              example: true
        smtp:
          type: object
          properties:
            ok:
              type: boolean
              example: true
            error:
              type: string
              nullable: true
        inBlocklist:
          type: boolean
          example: false
        inTrustedDomains:
          type: boolean
          example: true
        isRole:
          type: boolean
          example: false
        isDisposable:
          type: boolean
          example: false
        hasSPF:
          type: boolean
          example: true
        hasDMARC:
          type: boolean
          example: true
        domainAgeYears:
          type: integer
          example: 5
    SingleEmailResponse:
      type: object
      properties:
        email:
          type: string
          example: "test@example.com"
        percentage:
          type: number
          example: 85
        info:
          $ref: '#/components/schemas/EmailCheckResult'
    BulkEmailResponseItem:
      type: object
      properties:
        percentage:
          type: number
          example: 85
        info:
          oneOf:
            - type: string
              example: "Invalid syntax"
            - type: string
              example: "No MX records"
            - $ref: '#/components/schemas/EmailCheckResult'
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          example: 200
        message:
          type: string
          example: "success"
        body:
          oneOf:
            - $ref: '#/components/schemas/SingleEmailResponse'
            - type: array
              items:
                $ref: '#/components/schemas/BulkEmailResponseItem'
paths:
  /check:
    get:
      summary: Check a single email
      description: Returns validation info for a single email
      security:
        - RapidAPIKey: []
      parameters:
        - in: query
          name: email
          schema:
            type: string
          required: true
          description: The email to check
        - in: query
          name: skipSMTP
          schema:
            type: boolean
            default: false
          description: Skip SMTP check
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Missing or invalid parameter
        '422':
          description: Email failed validation
        '401':
          description: Unauthorized (missing or invalid RapidAPI key)
  /check-bulk:
    post:
      summary: Check multiple emails
      description: Accepts JSON with emails array and skipSMTP option
      security:
        - RapidAPIKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                skipSMTP:
                  type: boolean
                  default: false
                emails:
                  type: array
                  items:
                    type: string
                  example:
                    - "test1@example.com"
                    - "test2@example.com"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Missing or invalid emails array
        '401':
          description: Unauthorized (missing or invalid RapidAPI key)
        '422':
          description: One or more emails failed validation